In [5]:
# Examples 
# 1. Timing a model Training Function 

import time 
def timing_decorator(func): 
    def wrapper(*args, **kwargs): 
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"{func.__name__} took {end_time - start_time:.4f} secodns")
        return result 
    return wrapper 

@timing_decorator
def train_model(model, X_train, y_train): 
    model.fit(X_train, y_train)



# Example usage with a scikit learn model 
# import sklearn as scikit_learn
from sklearn.ensemble import RandomForestClassifier 
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=100, n_features=20)
model = RandomForestClassifier()

train_model(model, X, y)

train_model took 0.2132 secodns


In [6]:
# Caching Preprocessing Results 
from functools import lru_cache 
import numpy as np 


@lru_cache(maxsize = None)
def preprocess_data(seed): 
    np.random.seed(seed)
    data = np.random.rand(100, 20)
    labels = np.random.randint(0, 2, 1000)
    return data,labels

# Using the decorator 
data, labels = preprocess_data(42)


# Key point: if preprocess_data is called again with the same seed, the cached result is returned. 

In [11]:
# Input Vlaidation for Preprocessing 
# You can enforce that data meets certain conditions before processing 

def validate_input(func): 
    def wrapper(X, y, *args, **kwargs): 
        if X.shape[0] != y.shape[0]: 
            raise ValueError("Number of sample in X and y must be the same")
        if X.ndim != 2: 
            raise ValueError("X must be a 2D array")
        return func(X, y, *args, **kwargs)
    return wrapper 

@validate_input 
def preprocess(X, y): 
    # perform preprocessing 
    print("Preprocessing data..")
    return X/X.max(axis=0), y


# Example usage 
import numpy as np 
X = np.random.rand(100, 10)
y = np.random.randint(0, 2, 100)

preprocess(X, y) # Works fine 
# Preprocess(X[:50], y) # Raises ValueError

Preprocessing data..


(array([[8.25430837e-01, 1.38319672e-01, 5.82723285e-01, 5.09286754e-01,
         1.45485294e-01, 6.26775791e-01, 2.74257665e-01, 4.96512729e-01,
         8.28928084e-02, 4.59787420e-01],
        [3.14708706e-01, 8.29403960e-01, 5.71773434e-02, 4.21735797e-01,
         4.62906665e-01, 7.28232949e-01, 5.75582988e-01, 6.79081824e-01,
         7.82909662e-01, 8.62584492e-01],
        [3.22320151e-01, 5.42617167e-01, 8.43036527e-01, 9.96845938e-01,
         8.98202863e-01, 3.73120597e-01, 1.95606752e-01, 4.98098668e-01,
         7.47234788e-01, 4.92787029e-01],
        [4.96180590e-01, 8.45388515e-01, 3.62663560e-01, 8.66220475e-01,
         4.10776059e-01, 3.29694013e-01, 4.55013971e-01, 7.76010637e-01,
         1.26952314e-01, 1.96506130e-01],
        [9.77042947e-01, 1.76990243e-01, 5.69706302e-01, 5.83644058e-01,
         4.94404212e-01, 6.47614895e-01, 2.30345143e-01, 5.62493946e-01,
         3.74980124e-01, 6.61960042e-01],
        [1.45023088e-01, 5.75752442e-01, 1.85916171e-01, 2.8

In [20]:
# Adding Logging to ML Pipelines 
# you might want to log the execution flow of machine learning pipeline for debugging or monitoring 

def log_decorator(func): 
    def wrapper(*args, **kwargs): 
        print(f"Exchange {func.__name__}")
        result = func(*args, **kwargs)
    return wrapper


@log_decorator
def train_model(model, X_train, y_train): 
    return model.fit(X_train, y_train)

@log_decorator 
def evaluate_model(model, X_test, y_test): 
    return model.score(X_test, y_test)


# Example usage 
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split 

X, y = make_classification(n_samples=1000, n_features = 20)
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size = 0.2)


model = LogisticRegression()
train_model(model, X_train, y_train)
accuracy = evaluate_model(model, X_test, y_test)
print(f"model Accuracy: {accuracy}")

Exchange train_model
Exchange evaluate_model
model Accuracy: None


In [22]:
# Dynamic Hyperparameter Tuning 
# Decorator can help track hyperparameter configurations used during experimenrts. 
def track_hyperparameters(func): 
    def wrapper(*args, **kwargs): 
        print(f'Hyperparameters: {kwargs}')
        return func(*args, **kwargs)
    return wrapper 

@track_hyperparameters
def train_model_with_params(model, X_train, y_train, **params): 
    model.set_params(**params)
    model.fit(X_train, y_train)

# Example usage 
model = RandomForestClassifier()
train_model_with_params(model, X_train, y_train, n_estimators = 100, max_depth = 10)


Hyperparameters: {'n_estimators': 100, 'max_depth': 10}


In [25]:
# custom Decorator for Metrics 
# You can create a decorator to compute and print performance metrics automatically. 

def metrics_decorator(func): 
    def wrapper(*args, **kwargs): 
        y_true, y_pred = func(*args, **kwargs)
        from sklearn.metrics import accuracy_score, precision_score
        print(f"Accuracy: {accuracy_score(y_true, y_pred):.2f}")
        print(f"Precision: {precision_score(y_true, y_pred):.2f}")
        return y_true, y_pred 
    return wrapper 

@metrics_decorator 
def make_predictions(model, X_test, y_test): 
    y_pred  = model.predict(X_test)
    return y_test, y_pred 

# Example usage 
model.fit(X_train, y_train)
make_predictions(model, X_test, y_test)

Accuracy: 0.94
Precision: 0.90


(array([1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
        1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 0]),
 array([1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
        1, 0, 1, 0, 0,